### ISSUE TITLE
Fix CI builds

### ISSUE THREAD

**Issue by yowidin** [conan-burrito/boost#1]
- [ ] watchOS
```
./boost/test/impl/execution_monitor.ipp:800:34: error: 'sigaltstack' is unavailable: not available on watchOS
```

Seems like we can turn it off using an appropriate flag:
https://www.boost.org/doc/libs/1_74_0/libs/test/doc/html/boost_test/utf_reference/rt_param_reference/use_alt_stack.html

---

- [ ] Linux
```
2020-08-25T19:36:15.5153979Z boost/1.74.0@conan-burrito/stable: WARN: Build folder /home/runner/.conan/data/boost/1.74.0/conan-burrito/stable/build/054dd3a3cd21b3ae143835ffc88fc0d510105d33
2020-08-25T19:36:15.5429656Z Traceback (most recent call last):
2020-08-25T19:36:15.5431604Z   File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/conans/errors.py", line 34, in conanfile_exception_formatter
2020-08-25T19:36:15.5433182Z     yield
2020-08-25T19:36:15.5434144Z   File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/conans/client/conanfile/build.py", line 16, in run_build_method
2020-08-25T19:36:15.5434429Z     conanfile.build()
2020-08-25T19:36:15.5435020Z   File "/home/runner/.conan/data/boost/1.74.0/conan-burrito/stable/export/conanfile.py", line 250, in build
2020-08-25T19:36:15.5435279Z     self._write_user_config_jam()
2020-08-25T19:36:15.5435904Z   File "/home/runner/.conan/data/boost/1.74.0/conan-burrito/stable/export/conanfile.py", line 340, in _write_user_config_jam
2020-08-25T19:36:15.5436661Z     contents += '\nusing "%s" : %s : ' % (self._toolset, self._toolset_version)
2020-08-25T19:36:15.5437305Z   File "/home/runner/.conan/data/boost/1.74.0/conan-burrito/stable/export/conanfile.py", line 218, in _toolset_version
2020-08-25T19:36:15.5437586Z     elif compiler == "gcc" and major >= 5:
2020-08-25T19:36:15.5438032Z TypeError: '>=' not supported between instances of 'str' and 'int'
```

**Comment by yowidin** [comment]
Fixed in https://github.com/conan-burrito/boost/commit/871ea2ce6cbcbbe0af30ba9d8cbaa91f1d248c2e
